<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useAdminStore } from '@/stores/admin'

const admin = useAdminStore()

interface SessionReport {
  id: string
  version: string
  date: string
  title: string
  summary: string
  agents_used: string[]
  jobs_found: number
  jobs_scored: number
  jobs_matched: number
  apis_called: string[]
  duration_mins: number
  actions: string[]
  status: 'completed' | 'running' | 'failed'
}

const reports = ref<SessionReport[]>([])
const showDetail = ref(false)
const detailReport = ref<SessionReport | null>(null)
// Reports auto-generate from agent logs

onMounted(() => {
  // Load reports from agent logs
  admin.fetchJobAgentLogs()
  admin.fetchJobListings()
  admin.fetchJobApplications()
  buildReports()
})

function buildReports() {
  // Generate session reports from agent logs grouped by run_id
  const runs = new Map<string, any[]>()
  for (const log of admin.jobAgentLogs) {
    if (!runs.has(log.run_id)) runs.set(log.run_id, [])
    runs.get(log.run_id)!.push(log)
  }

  const builtReports: SessionReport[] = []
  let version = 1
  for (const [runId, logs] of runs) {
    const firstLog = logs[0] as any
    const lastLog = logs[logs.length - 1] as any
    const found = logs.reduce((s: number, l: { jobs_found: number }) => s + l.jobs_found, 0)
    const matched = logs.reduce((s: number, l: { jobs_matched: number }) => s + l.jobs_matched, 0)

    builtReports.push({
      id: runId,
      version: `v${version++}.0`,
      date: firstLog.created_at,
      title: `Agent Run ${runId.slice(0, 8)}`,
      summary: logs.map((l: any) => l.message).filter(Boolean).join('. '),
      agents_used: [...new Set(logs.map((l: any) => l.step))] as string[],
      jobs_found: found,
      jobs_scored: matched,
      jobs_matched: matched,
      apis_called: ['JSearch', 'Himalayas', 'RemoteOK', 'Arbeitnow', 'HackerNews', 'LinkedIn'],
      duration_mins: lastLog.completed_at ? Math.round((new Date(lastLog.completed_at).getTime() - new Date(firstLog.started_at).getTime()) / 60000) : 0,
      actions: logs.map((l: any) => `${l.step}: ${l.message || l.status}`),
      status: logs.every((l: any) => l.status === 'completed') ? 'completed' as const : logs.some((l: any) => l.status === 'running') ? 'running' as const : 'failed' as const,
    })
  }

  // Add a daily summary report
  const today = new Date().toISOString().split('T')[0]
  const todayJobs = admin.jobListings.filter(j => j.created_at.startsWith(today)).length
  const todayApps = admin.jobApplications.filter(a => a.created_at.startsWith(today)).length
  if (todayJobs > 0 || todayApps > 0 || builtReports.length === 0) {
    builtReports.unshift({
      id: `daily-${today}`,
      version: `v${version}.0`,
      date: new Date().toISOString(),
      title: `Daily Report — ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`,
      summary: `${admin.jobListings.length} total jobs in pipeline. ${todayJobs} new today. ${admin.jobApplications.length} applications tracked. ${admin.jobListings.filter(j => j.match_score !== null).length} jobs scored.`,
      agents_used: ['Scout', 'Classifier', 'Matcher', 'Research', 'Writer', 'Nurture'],
      jobs_found: admin.jobListings.length,
      jobs_scored: admin.jobListings.filter(j => j.match_score !== null).length,
      jobs_matched: admin.jobListings.filter(j => (j.match_score || 0) >= 60).length,
      apis_called: ['JSearch', 'Himalayas', 'RemoteOK', 'Remotive', 'Arbeitnow', 'HackerNews', 'LinkedIn', 'FAISS', 'GPT/Gemini'],
      duration_mins: 0,
      actions: [`Total jobs: ${admin.jobListings.length}`, `Scored: ${admin.jobListings.filter(j => j.match_score !== null).length}`, `Applications: ${admin.jobApplications.length}`],
      status: 'completed',
    })
  }

  reports.value = builtReports.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
}

function viewReport(r: SessionReport) { detailReport.value = r; showDetail.value = true }

function downloadWord(r: SessionReport) {
  const content = `NEURALYX PHANTOM SESSION REPORT\n${'='.repeat(40)}\n\nVersion: ${r.version}\nDate: ${new Date(r.date).toLocaleDateString()}\nTitle: ${r.title}\nStatus: ${r.status}\n\nSUMMARY\n${'-'.repeat(20)}\n${r.summary}\n\nAGENTS USED\n${'-'.repeat(20)}\n${r.agents_used.join(', ')}\n\nMETRICS\n${'-'.repeat(20)}\nJobs Found: ${r.jobs_found}\nJobs Scored: ${r.jobs_scored}\nJobs Matched: ${r.jobs_matched}\nDuration: ${r.duration_mins} minutes\n\nAPIs CALLED\n${'-'.repeat(20)}\n${r.apis_called.join(', ')}\n\nACTIONS\n${'-'.repeat(20)}\n${r.actions.join('\n')}\n\n${'='.repeat(40)}\nGenerated by NEURALYX AI Agent System`
  const blob = new Blob([content], { type: 'application/msword' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = `phantom-report-${r.version}-${r.id.slice(0, 8)}.doc`
  a.click(); URL.revokeObjectURL(url)
}

function downloadPDF(r: SessionReport) {
  // Generate printable HTML and trigger print dialog (saves as PDF)
  const html = `<html><head><title>Phantom Report ${r.version}</title><style>body{font-family:Arial;padding:40px;color:#333}h1{color:#6b46c1}h2{color:#555;border-bottom:1px solid #ddd;padding-bottom:5px}table{width:100%;border-collapse:collapse;margin:10px 0}td{padding:5px 10px;border:1px solid #eee}.badge{background:#f0f0ff;padding:2px 8px;border-radius:4px;font-size:12px}</style></head><body><h1>NEURALYX Phantom Report</h1><p><strong>Version:</strong> ${r.version} | <strong>Date:</strong> ${new Date(r.date).toLocaleDateString()} | <strong>Status:</strong> ${r.status}</p><h2>Summary</h2><p>${r.summary}</p><h2>Metrics</h2><table><tr><td>Jobs Found</td><td><strong>${r.jobs_found}</strong></td><td>Jobs Scored</td><td><strong>${r.jobs_scored}</strong></td></tr><tr><td>Jobs Matched</td><td><strong>${r.jobs_matched}</strong></td><td>Duration</td><td><strong>${r.duration_mins}min</strong></td></tr></table><h2>Agents Used</h2><p>${r.agents_used.map(a => `<span class="badge">${a}</span>`).join(' ')}</p><h2>APIs Called</h2><p>${r.apis_called.map(a => `<span class="badge">${a}</span>`).join(' ')}</p><h2>Actions Log</h2><ul>${r.actions.map(a => `<li>${a}</li>`).join('')}</ul><hr><p style="color:#999;font-size:11px">Generated by NEURALYX AI Agent System — ${new Date().toLocaleString()}</p></body></html>`
  const w = window.open('', '_blank')
  if (w) { w.document.write(html); w.document.close(); setTimeout(() => w.print(), 500) }
}

function timeAgo(d: string) {
  const diff = Date.now() - new Date(d).getTime()
  const hrs = Math.floor(diff / 3600000)
  if (hrs < 1) return 'Just now'
  if (hrs < 24) return `${hrs}h ago`
  const days = Math.floor(hrs / 24)
  if (days < 7) return `${days}d ago`
  return new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <div>
        <h2 class="text-2xl font-bold text-white">Phantom Reports</h2>
        <p class="text-sm text-gray-400 mt-1">AI agent session reports — auto-generated every 24 hours</p>
      </div>
      <div class="flex items-center gap-2 text-xs text-gray-500">
        <span class="w-2 h-2 rounded-full bg-green-400 animate-pulse"></span>
        {{ reports.length }} reports
      </div>
    </div>

    <!-- Registration Checklist -->
    <div class="glass-dark rounded-xl p-4 border border-yellow-500/20 mb-6">
      <h3 class="text-xs text-yellow-400 font-semibold uppercase tracking-wider mb-3">Platform Registration Checklist</h3>
      <div class="grid grid-cols-2 lg:grid-cols-4 gap-2">
        <div v-for="p in [
          { name: 'JobStreet PH', url: 'ph.jobstreet.com', done: false },
          { name: 'Kalibrr', url: 'kalibrr.com', done: false },
          { name: 'OnlineJobs.ph', url: 'onlinejobs.ph', done: false },
          { name: 'Bossjob', url: 'bossjob.ph', done: false },
          { name: 'VirtualStaff.ph', url: 'virtualstaff.ph', done: false },
          { name: 'Mynimo', url: 'mynimo.com', done: false },
          { name: 'BruntWork', url: 'bruntworkcareers.co', done: false },
          { name: 'PhilJobNet', url: 'philjobnet.gov.ph', done: true },
          { name: 'Upwork', url: 'upwork.com', done: false },
          { name: 'Indeed PH', url: 'ph.indeed.com', done: false },
          { name: 'LinkedIn', url: 'linkedin.com', done: false },
          { name: 'Glassdoor', url: 'glassdoor.com', done: false },
        ]" :key="p.name" class="flex items-center gap-2 px-2 py-1.5 rounded bg-neural-800/50">
          <span class="w-3 h-3 rounded-full border" :class="p.done ? 'bg-green-500 border-green-500' : 'border-gray-600'" />
          <div class="min-w-0">
            <p class="text-[10px] text-white truncate">{{ p.name }}</p>
            <p class="text-[8px] text-gray-600">{{ p.url }}</p>
          </div>
        </div>
      </div>
      <p class="text-[9px] text-gray-500 mt-2">Email: gabrielalvin.jobs@gmail.com | Register with your resume details</p>
    </div>

    <!-- Reports Table -->
    <div v-if="reports.length === 0" class="text-center py-16 glass-dark rounded-xl border border-neural-700/50">
      <div class="text-4xl mb-3">👻</div>
      <h3 class="text-lg font-semibold text-white mb-2">No reports yet</h3>
      <p class="text-gray-500 text-sm">Run the AI Agent to generate your first session report.</p>
    </div>

    <div v-else class="glass-dark rounded-xl overflow-hidden border border-neural-700/50">
      <table class="w-full text-sm">
        <thead class="bg-neural-700/40">
          <tr>
            <th class="text-left px-4 py-3 text-gray-500 font-medium text-[10px] uppercase">Version</th>
            <th class="text-left px-4 py-3 text-gray-500 font-medium text-[10px] uppercase">Report</th>
            <th class="text-center px-4 py-3 text-gray-500 font-medium text-[10px] uppercase">Found</th>
            <th class="text-center px-4 py-3 text-gray-500 font-medium text-[10px] uppercase">Scored</th>
            <th class="text-center px-4 py-3 text-gray-500 font-medium text-[10px] uppercase">Matched</th>
            <th class="text-left px-4 py-3 text-gray-500 font-medium text-[10px] uppercase">Agents</th>
            <th class="text-left px-4 py-3 text-gray-500 font-medium text-[10px] uppercase">Status</th>
            <th class="text-left px-4 py-3 text-gray-500 font-medium text-[10px] uppercase">Date</th>
            <th class="text-right px-4 py-3 text-gray-500 font-medium text-[10px] uppercase">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="r in reports" :key="r.id" class="border-t border-neural-700/30 hover:bg-neural-700/20 transition-colors cursor-pointer" @click="viewReport(r)">
            <td class="px-4 py-3"><span class="px-2 py-0.5 rounded bg-cyber-purple/20 text-cyber-purple text-[10px] font-mono font-bold">{{ r.version }}</span></td>
            <td class="px-4 py-3">
              <p class="text-xs text-white font-medium">{{ r.title }}</p>
              <p class="text-[10px] text-gray-500 truncate max-w-[250px]">{{ r.summary }}</p>
            </td>
            <td class="px-4 py-3 text-center text-xs text-white">{{ r.jobs_found }}</td>
            <td class="px-4 py-3 text-center text-xs text-yellow-400">{{ r.jobs_scored }}</td>
            <td class="px-4 py-3 text-center text-xs text-green-400">{{ r.jobs_matched }}</td>
            <td class="px-4 py-3"><span class="text-[10px] text-gray-400">{{ r.agents_used.length }} agents</span></td>
            <td class="px-4 py-3">
              <span class="px-2 py-0.5 rounded-full text-[10px] font-medium capitalize"
                :class="r.status === 'completed' ? 'bg-green-500/15 text-green-400' : r.status === 'running' ? 'bg-blue-500/15 text-blue-400' : 'bg-red-500/15 text-red-400'">{{ r.status }}</span>
            </td>
            <td class="px-4 py-3 text-[10px] text-gray-500">{{ timeAgo(r.date) }}</td>
            <td class="px-4 py-3 text-right" @click.stop>
              <div class="flex items-center justify-end gap-1">
                <button @click="viewReport(r)" class="p-1.5 rounded hover:bg-neural-600 text-gray-500 hover:text-white transition-colors" title="View">
                  <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" /></svg>
                </button>
                <button @click="downloadWord(r)" class="p-1.5 rounded hover:bg-neural-600 text-gray-500 hover:text-blue-400 transition-colors" title="Download Word">
                  <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                </button>
                <button @click="downloadPDF(r)" class="p-1.5 rounded hover:bg-neural-600 text-gray-500 hover:text-red-400 transition-colors" title="View as PDF">
                  <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" /></svg>
                </button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Detail Modal -->
    <Teleport to="body">
      <div v-if="showDetail && detailReport" class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" @click.self="showDetail = false">
        <div class="glass-dark rounded-xl w-full max-w-2xl border border-neural-600 max-h-[85vh] flex flex-col">
          <div class="px-6 py-4 border-b border-neural-700 shrink-0 flex items-center justify-between">
            <div>
              <div class="flex items-center gap-2 mb-1">
                <span class="px-2 py-0.5 rounded bg-cyber-purple/20 text-cyber-purple text-xs font-mono font-bold">{{ detailReport.version }}</span>
                <span class="px-2 py-0.5 rounded-full text-[10px] font-medium capitalize"
                  :class="detailReport.status === 'completed' ? 'bg-green-500/15 text-green-400' : 'bg-blue-500/15 text-blue-400'">{{ detailReport.status }}</span>
              </div>
              <h3 class="text-lg font-bold text-white">{{ detailReport.title }}</h3>
              <p class="text-xs text-gray-400">{{ new Date(detailReport.date).toLocaleString() }}</p>
            </div>
            <div class="flex gap-1">
              <button @click="downloadWord(detailReport)" class="p-2 rounded-lg hover:bg-neural-600 text-gray-400 hover:text-blue-400" title="Word"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" /></svg></button>
              <button @click="downloadPDF(detailReport)" class="p-2 rounded-lg hover:bg-neural-600 text-gray-400 hover:text-red-400" title="PDF"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" /></svg></button>
              <button @click="showDetail = false" class="p-2 rounded-lg hover:bg-neural-600 text-gray-400 hover:text-white"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg></button>
            </div>
          </div>
          <div class="flex-1 overflow-y-auto p-6 space-y-4">
            <p class="text-sm text-gray-300">{{ detailReport.summary }}</p>
            <div class="grid grid-cols-3 gap-3">
              <div class="bg-neural-800/50 rounded-lg p-3 border border-neural-700/30 text-center">
                <p class="text-2xl font-bold text-white">{{ detailReport.jobs_found }}</p>
                <p class="text-[9px] text-gray-500 uppercase">Found</p>
              </div>
              <div class="bg-neural-800/50 rounded-lg p-3 border border-neural-700/30 text-center">
                <p class="text-2xl font-bold text-yellow-400">{{ detailReport.jobs_scored }}</p>
                <p class="text-[9px] text-gray-500 uppercase">Scored</p>
              </div>
              <div class="bg-neural-800/50 rounded-lg p-3 border border-neural-700/30 text-center">
                <p class="text-2xl font-bold text-green-400">{{ detailReport.jobs_matched }}</p>
                <p class="text-[9px] text-gray-500 uppercase">Matched</p>
              </div>
            </div>
            <div>
              <h4 class="text-xs text-gray-400 uppercase tracking-wider mb-2">Agents Used</h4>
              <div class="flex flex-wrap gap-1.5">
                <span v-for="a in detailReport.agents_used" :key="a" class="px-2.5 py-1 rounded-full text-xs bg-cyber-purple/15 text-cyber-purple capitalize">{{ a }}</span>
              </div>
            </div>
            <div>
              <h4 class="text-xs text-gray-400 uppercase tracking-wider mb-2">APIs Called</h4>
              <div class="flex flex-wrap gap-1.5">
                <span v-for="a in detailReport.apis_called" :key="a" class="px-2.5 py-1 rounded-full text-xs bg-cyan-500/15 text-cyan-400">{{ a }}</span>
              </div>
            </div>
            <div>
              <h4 class="text-xs text-gray-400 uppercase tracking-wider mb-2">Actions Log</h4>
              <div class="space-y-1">
                <div v-for="(action, idx) in detailReport.actions" :key="idx" class="flex items-start gap-2 text-xs text-gray-400">
                  <span class="text-[10px] text-gray-600 shrink-0">{{ idx + 1 }}.</span>
                  <span>{{ action }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>
